if(EXISTS "/home/lx/VScode/GitHub/Vehicle-central-control-management-system/build_arm/test_FaultModule[1]_tests.cmake")
  include("/home/lx/VScode/GitHub/Vehicle-central-control-management-system/build_arm/test_FaultModule[1]_tests.cmake")
else()
  add_test(test_FaultModule_NOT_BUILT test_FaultModule_NOT_BUILT)
endif()
