if(EXISTS "/home/lx/VScode/GitHub/Vehicle-central-control-management-system/build_riscv/test_Logger[1]_tests.cmake")
  include("/home/lx/VScode/GitHub/Vehicle-central-control-management-system/build_riscv/test_Logger[1]_tests.cmake")
else()
  add_test(test_Logger_NOT_BUILT test_Logger_NOT_BUILT)
endif()
