if(EXISTS "/home/lx/VScode/GitHub/Vehicle-central-control-management-system/build_riscv/test_StatusModule[1]_tests.cmake")
  include("/home/lx/VScode/GitHub/Vehicle-central-control-management-system/build_riscv/test_StatusModule[1]_tests.cmake")
else()
  add_test(test_StatusModule_NOT_BUILT test_StatusModule_NOT_BUILT)
endif()
