#include "ConfigManager.hpp"
#include "Car_Log.hpp"
#include <cerrno>
#include <cstring>
#include <fcntl.h>
#include <fstream>
#include <filesystem>
#include <sstream>
#include <string>
#include <system_error>
#include <unistd.h>

namespace {

std::string trim(const std::string& s) {
    const std::string spaces = " \t\r\n";
    const auto begin = s.find_first_not_of(spaces);
    if (begin == std::string::npos) {
        return "";
    }
    const auto end = s.find_last_not_of(spaces);
    return s.substr(begin, end - begin + 1);
}

bool writeAll(int fd, const char* data, size_t size) {
    size_t written = 0;
    while (written < size) {
        const ssize_t n = ::write(fd, data + written, size - written);
        if (n <= 0) {
            return false;
        }
        written += static_cast<size_t>(n);
    }
    return true;
}

uint8_t parseGear(const std::string& text) {
    if (text == "P") return static_cast<uint8_t>(Car::Gear::P);
    if (text == "R") return static_cast<uint8_t>(Car::Gear::R);
    if (text == "N") return static_cast<uint8_t>(Car::Gear::N);
    if (text == "D") return static_cast<uint8_t>(Car::Gear::D);
    return static_cast<uint8_t>(Car::Gear::P);
}

} // namespace

ConfigManager& ConfigManager::getInstance() {
    static ConfigManager instance;
    return instance;
}

void ConfigManager::initDefaults() {
    std::lock_guard<std::mutex> lock(m_mutex);
    m_data.status.battery_voltage = 12.0f;
    m_data.status.fuel = 50.0f;
    m_data.status.gear = static_cast<uint8_t>(Car::Gear::P);
    m_data.status.hand_brake = 1;
    m_data.status.oil_temp = 40.0f;
    m_data.status.water_temp = 30.0f;
    m_data.air.temp_set = 20;
}

ConfigManager::FullCarData ConfigManager::getData() {
    std::lock_guard<std::mutex> lock(m_mutex);
    return m_data;
}

void ConfigManager::setData(const FullCarData& data) {
    std::lock_guard<std::mutex> lock(m_mutex);
    m_data = data;
}

// 完整无删减的序列化落盘功能
bool ConfigManager::save() {
    std::lock_guard<std::mutex> lock(m_mutex);
    const std::string temp_path = std::string(Car::INI_FILE_PATH) + ".tmp";
    std::ostringstream content;

    content << "# Car configuration file\n";
    content << "# This file is automatically generated, do not edit manually\n\n";

    content << "[door]\n"
            << "door_front_left = " << static_cast<int>(m_data.door.front_left) << "\n"
            << "door_front_right = " << static_cast<int>(m_data.door.front_right) << "\n"
            << "door_back_left = " << static_cast<int>(m_data.door.back_left) << "\n"
            << "door_back_right = " << static_cast<int>(m_data.door.back_right) << "\n"
            << "door_trunk = " << static_cast<int>(m_data.door.trunk) << "\n"
            << "lock_status = " << static_cast<int>(m_data.door.lock_status) << "\n\n";

    content << "[status]\n"
            << "speed = " << m_data.status.speed << "\n"
            << "rpm = " << m_data.status.rpm << "\n"
            << "water_temp = " << m_data.status.water_temp << "\n"
            << "oil_temp = " << m_data.status.oil_temp << "\n"
            << "fuel = " << m_data.status.fuel << "\n"
            << "battery_voltage = " << m_data.status.battery_voltage << "\n"
            << "gear = " << Car::gearToText(m_data.status.gear) << "\n"
            << "gear_code = " << static_cast<int>(m_data.status.gear) << "\n"
            << "hand_brake = " << static_cast<int>(m_data.status.hand_brake) << "\n\n";

    content << "[air]\n"
            << "ac_switch = " << static_cast<int>(m_data.air.ac_switch) << "\n"
            << "fan_speed = " << static_cast<int>(m_data.air.fan_speed) << "\n"
            << "temp_set = " << m_data.air.temp_set << "\n"
            << "inner_cycle = " << static_cast<int>(m_data.air.inner_cycle) << "\n\n";

    content << "[fault]\n"
            << "fault_count = " << static_cast<int>(m_data.fault.fault_count) << "\n"
            << "wring_light = " << static_cast<int>(m_data.fault.wring_light) << "\n";
    for (int i = 0; i < Car::MAX_FAULT_CODE; ++i) {
        content << "fault_code_" << i << " = " << m_data.fault.fault_codes[i] << "\n";
    }

    const std::string buffer = content.str();
    const int fd = ::open(temp_path.c_str(), O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) {
        LOG_ERROR("Failed to open temp file for writing: %s", temp_path.c_str());
        return false;
    }

    bool ok = writeAll(fd, buffer.data(), buffer.size());
    if (ok && ::fsync(fd) != 0) {
        ok = false;
    }

    if (::close(fd) != 0) {
        ok = false;
    }

    if (!ok) {
        LOG_ERROR("Failed to flush temp config file: %s", std::strerror(errno));
        return false;
    }

    if (::rename(temp_path.c_str(), Car::INI_FILE_PATH) != 0) {
        LOG_ERROR("Failed to overwrite config file: %s", std::strerror(errno));
        return false;
    }

    std::filesystem::path ini_path(Car::INI_FILE_PATH);
    const std::string dir = ini_path.parent_path().empty() ? "." : ini_path.parent_path().string();
    const int dir_fd = ::open(dir.c_str(), O_RDONLY | O_DIRECTORY);
    if (dir_fd >= 0) {
        if (::fsync(dir_fd) != 0) {
            LOG_WARN("Directory fsync failed for %s: %s", dir.c_str(), std::strerror(errno));
        }
        ::close(dir_fd);
    }

    LOG_INFO("Successfully synced and saved car info to %s", Car::INI_FILE_PATH);
    return true;
}

bool ConfigManager::load() {
    std::lock_guard<std::mutex> lock(m_mutex);
    std::ifstream in(Car::INI_FILE_PATH);
    if (!in.is_open()) {
        LOG_WARN("Config file not found: %s", Car::INI_FILE_PATH);
        return false;
    }

    FullCarData loaded = m_data;
    std::string section;
    std::string line;

    while (std::getline(in, line)) {
        line = trim(line);
        if (line.empty() || line[0] == '#' || line[0] == ';') {
            continue;
        }

        if (line.front() == '[' && line.back() == ']') {
            section = trim(line.substr(1, line.size() - 2));
            continue;
        }

        const auto eq_pos = line.find('=');
        if (eq_pos == std::string::npos) {
            continue;
        }

        const std::string key = trim(line.substr(0, eq_pos));
        const std::string value = trim(line.substr(eq_pos + 1));

        try {
            if (section == "door") {
                if (key == "door_front_left") loaded.door.front_left = static_cast<uint8_t>(std::stoi(value));
                else if (key == "door_front_right") loaded.door.front_right = static_cast<uint8_t>(std::stoi(value));
                else if (key == "door_back_left") loaded.door.back_left = static_cast<uint8_t>(std::stoi(value));
                else if (key == "door_back_right") loaded.door.back_right = static_cast<uint8_t>(std::stoi(value));
                else if (key == "door_trunk") loaded.door.trunk = static_cast<uint8_t>(std::stoi(value));
                else if (key == "lock_status") loaded.door.lock_status = static_cast<uint8_t>(std::stoi(value));
            } else if (section == "status") {
                if (key == "speed") loaded.status.speed = std::stof(value);
                else if (key == "rpm") loaded.status.rpm = std::stoi(value);
                else if (key == "water_temp") loaded.status.water_temp = std::stof(value);
                else if (key == "oil_temp") loaded.status.oil_temp = std::stof(value);
                else if (key == "fuel") loaded.status.fuel = std::stof(value);
                else if (key == "battery_voltage") loaded.status.battery_voltage = std::stof(value);
                else if (key == "gear") loaded.status.gear = parseGear(value);
                else if (key == "gear_code") loaded.status.gear = static_cast<uint8_t>(std::stoi(value));
                else if (key == "hand_brake") loaded.status.hand_brake = static_cast<uint8_t>(std::stoi(value));
            } else if (section == "air") {
                if (key == "ac_switch") loaded.air.ac_switch = static_cast<uint8_t>(std::stoi(value));
                else if (key == "fan_speed") loaded.air.fan_speed = static_cast<uint8_t>(std::stoi(value));
                else if (key == "temp_set") loaded.air.temp_set = std::stoi(value);
                else if (key == "inner_cycle") loaded.air.inner_cycle = static_cast<uint8_t>(std::stoi(value));
            } else if (section == "fault") {
                if (key == "fault_count") {
                    loaded.fault.fault_count = static_cast<uint8_t>(std::stoi(value));
                } else if (key == "wring_light") {
                    loaded.fault.wring_light = static_cast<uint8_t>(std::stoi(value));
                } else if (key.rfind("fault_code_", 0) == 0) {
                    const int idx = std::stoi(key.substr(11));
                    if (idx >= 0 && idx < Car::MAX_FAULT_CODE) {
                        loaded.fault.fault_codes[idx] = static_cast<uint16_t>(std::stoi(value));
                    }
                }
            }
        } catch (const std::exception&) {
            LOG_WARN("Invalid config entry ignored: [%s] %s=%s", section.c_str(), key.c_str(), value.c_str());
        }
    }

    m_data = loaded;
    LOG_INFO("Loaded persisted config from %s", Car::INI_FILE_PATH);
    return true;
}